export const recommendationMap = {
  sherwani: ["Jooti", "dupatta", "mojari"],
  jam: ["bread", "butter", "cracker"],
  kurta: ["pyjama", "mojari", "stole"],
  jeans: ["belt", "t-shirt", "wallet"],
  shoes: ["socks", "shoe polish", "insole"],
  sari: ["blouse", "petticoat", "dupatta"],
  bread: ["jam", "butter", "cheese"],
  maggi: ["bread", "biscuits", "sauces"],
  biscuit: ["tea", "jam", "custard"],
  mobile: ["charger", "case", "earphones"],
  charger: ["powerbank", "cable", "adapter"],
  furniture: ["cushion", "cover", "care kit"],
  mattress: ["bedsheet", "pillow", "protector"],
  detergent: ["softener", "brush", "cleaner"],
  shampoo: ["conditioner", "soap", "hair oil"],
  kurta_pajama: ["mojari", "stole"],
  sherwani_set: ["jooti", "dupatta"],
  accessories: ["packaging", "gift wrap"],
};
export const categorySeeds = {
  Clothing: ["sherwani", "kurta", "jeans", "sari", "shoes", "dupatta", "blouse", "pyjama"],
  Grocery: ["jam", "bread", "maggi", "biscuit", "detergent"],
  "Mobile Accessories": ["charger", "case", "earphones", "powerbank"],
  Furniture: ["mattress", "cushion", "cover"],
  Electrical: ["charger", "adapter", "bulb"],
  Cosmetics: ["shampoo", "conditioner", "soap"],
};
export const commonSynonyms = {
  sherwani: ["sherwani", "rajwadi", "traditional sherwani", "wedding sherwani"],
  kurta: ["kurta", "kurta pajama", "kurta pyjama", "kurta set"],
  jeans: ["jeans", "denim"],
  shoes: ["shoes", "footwear", "mojari", "jutti"],
  maggi: ["maggi", "maggie", "instant noodles", "noodles"],
  jam: ["jam", "fruit preserve", "preserve"],
  bread: ["bread", "loaf"],
  mobile: ["mobile", "phone", "cellphone"],
  charger: ["charger", "adapter", "charging"],
  detergent: ["detergent", "wash", "soap powder"],
};
